name: linux
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

runs:
  using: 'docker'
  image: alpine

jobs:
  build:
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: source script-linux.sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
